# Generated by Django 4.2.5 on 2023-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ['serial'], 'verbose_name': 'Робот', 'verbose_name_plural': 'Роботы'},
        ),
        migrations.RemoveField(
            model_name='robot',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='robot',
            name='is_exists',
            field=models.BooleanField(default=True),
        ),
    ]
