# Generated by Django 4.2.5 on 2023-09-26 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_alter_robot_created_alter_robot_serial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
